// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Training.Persistence.DbContexts;

#nullable disable

namespace Training.Persistence.Migrations
{
    [DbContext(typeof(CourseContext))]
    [Migration("20240715120009_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Training.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxNumberOfStudents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef14acbe-35fb-4593-b912-c598625d3d29"),
                            MaxNumberOfStudents = 200,
                            Name = "IA",
                            StartDate = new DateTime(2024, 7, 15, 14, 0, 9, 587, DateTimeKind.Local).AddTicks(7260)
                        },
                        new
                        {
                            Id = new Guid("b5067a9b-4b7a-4c79-b5d4-d978955ceaca"),
                            MaxNumberOfStudents = 5000,
                            Name = "Ingles",
                            StartDate = new DateTime(2024, 7, 15, 14, 0, 9, 587, DateTimeKind.Local).AddTicks(7334)
                        },
                        new
                        {
                            Id = new Guid("3b9c895c-8dd9-41f8-8124-c2d43d623b81"),
                            MaxNumberOfStudents = 30,
                            Name = "Microservicios",
                            StartDate = new DateTime(2024, 7, 15, 14, 0, 9, 587, DateTimeKind.Local).AddTicks(7338)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
